name: WordPress Plugin Unit test matrix

on:
  push:
    branches:
      - 'test-matrix'

jobs:
  phpunit:
    name: WordPress ${{ matrix.wordpress }} * PHP v${{ matrix.php }} * ${{ matrix.os }} * Multisite ${{ matrix.multisite }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ ubuntu-20.04 ]
        php: [ '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2' ]
        wordpress: [ '5.0', '5.1', '5.2', '5.3', '5.4', '5.5', '5.6', '5.7', '5.8', '5.9', '6.0', '6.1', '6.2', latest, nightly ]
        multisite: [ 0 ]
        include:
          # Trying to access array offset on value of type bool on PHP 7.4
          - allow_failures: "true"
            php: '7.4'
            wordpress: '5.2'

          # Function get_magic_quotes_gpc() is deprecated
          - allow_failures: "true"
            php: '7.4'
            wordpress: '5.0'

          - allow_failures: "true"
            php: '7.4'
            wordpress: '5.1'

        exclude:
          # PHP 8.0+ is not compatible with PHPUnit 7.x. on WordPress versions prior to 5.8 and should not be tested.
          - php: '8.0'
            wordpress: '5.8'
          - php: '8.0'
            wordpress: '5.7'
          - php: '8.0'
            wordpress: '5.6'
          - php: '8.0'
            wordpress: '5.5'
          - php: '8.0'
            wordpress: '5.4'
          - php: '8.0'
            wordpress: '5.3'
          - php: '8.0'
            wordpress: '5.2'
          - php: '8.0'
            wordpress: '5.1'
          - php: '8.0'
            wordpress: '5.0'

          - php: '8.1'
            wordpress: '5.8'
          - php: '8.1'
            wordpress: '5.7'
          - php: '8.1'
            wordpress: '5.6'
          - php: '8.1'
            wordpress: '5.5'
          - php: '8.1'
            wordpress: '5.4'
          - php: '8.1'
            wordpress: '5.3'
          - php: '8.1'
            wordpress: '5.2'
          - php: '8.1'
            wordpress: '5.1'
          - php: '8.1'
            wordpress: '5.0'

          - php: '8.2'
            wordpress: '5.8'
          - php: '8.2'
            wordpress: '5.7'
          - php: '8.2'
            wordpress: '5.6'
          - php: '8.2'
            wordpress: '5.5'
          - php: '8.2'
            wordpress: '5.4'
          - php: '8.2'
            wordpress: '5.3'
          - php: '8.2'
            wordpress: '5.2'
          - php: '8.2'
            wordpress: '5.1'
          - php: '8.2'
            wordpress: '5.0'

    env:
      PHP_VERSION: ${{ matrix.php }}
      WP_VERSION: ${{ matrix.wordpress }}
      WP_MULTISITE: ${{ matrix.multisite }}

    services:
      database:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP v${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, php-mysql

      - name: apt --fix-broken install for PHP 7.0
        run: sudo apt --fix-broken install
        if: ${{ matrix.php == '7.0' }}

      - name: Install mbstring library for PHP 7.0
        # require ext-mbstring * -> it is missing from your system. Install or enable PHP's mbstring extension.
        run: sudo apt-get install php7.0-mbstring
        if: ${{ matrix.php == '7.0' }}

      - name: Install PHPUnit
        run: |
          # for PHP Compatibility - https://phpunit.de/supported-versions.html
          if [[ ${PHP_VERSION:0:1} == "8" ]] ; then
            composer global require "phpunit/phpunit=8.*"
          elif [[ $PHP_VERSION == "7.0" ]] ; then
            composer global require "phpunit/phpunit=5.7.*|6.*"
          # for WP_VERSION < 4.6 due to PHP Fatal error: Class 'PHPUnit_Framework_TestCase' not found
          elif [[ ${PHP_VERSION:0:1} == "7" ]] && [[ "$WP_VERSION" < 4.6* ]] ; then
            composer global require "phpunit/phpunit=5.7.*"
          # for WP_VERSION < 5.0 due to Fatal error: Class PHPUnit_Util_Test may not inherit from final class (PHPUnit\Util\Test)
          elif [[ ${PHP_VERSION:0:1} == "7" ]] && [[ "$WP_VERSION" < 5.0* ]] ; then
            composer global require "phpunit/phpunit=5.7.*|6.*"
          else
            composer global require "phpunit/phpunit=4.8.*|5.4.*|5.7.*|6.*|7.*"
          fi

      - name: Install PHPUnit Polyfills library
        run: composer global require "yoast/phpunit-polyfills=1.0.3"

      - name: Install wp tests
        run: bash bin/install-wp-tests.sh wordpress_test root root 0.0.0.0:3306 $WP_VERSION

      - name: Run PHPUnit - WordPress ${{ matrix.wordpress }} * Multisite ${{ matrix.multisite }}
        run: |
          if [[ $PHP_VERSION == "5.6" ]] || [[ $PHP_VERSION == "7.0" ]] ; then
            phpunit --configuration phpunit-legacy.xml
          else
            phpunit
          fi
        continue-on-error: ${{ matrix.allow_failures == 'true' }}
